### ISSUE TITLE
Issue with Debug

### ISSUE THREAD

**Issue by michaelcullum** [phpBB-Blog/phpBB-Blog#3]
[phpBB Debug] PHP Notice: in file /includes/hooks/hook_phpbb_blog.php on line 58: Undefined index: blog_title

in UMIL File. The code is:

```
// Assign the blog's main template variables
$template->assign_vars(array(
    'U_BLOG'                => append_sid("{$phpbb_root_path}blog.$phpEx"),
    'OVERALL_BLOG_TITLE'    => $config['blog_title'],
));
```

**Comment by imkingdavid** [comment]
This code is being run by the hook on every page, including the UMIL file, which is because it is looking for a config setting called 'blog_title', which doesn't exist until AFTER UMIL is run. So the fix would be to put something in the hook file to prevent registering the hook inside UMIL. An example is in my TMM hook file at the bottom.

**Comment by michaelcullum** [comment]
Yeh, I worked this out. It was just an issue with a line in UMIL, the hook and an syntax error.

**Comment by michaelcullum** [comment]
Fixed with http://github.com/phpBB-Blog/phpBB-Blog/commit/5af4acea6f86fc2e02fa4756b2da07c0253e4a78
